### ISSUE TITLE
Signature scanning

### ISSUE THREAD

**Issue by lurumdare** [hasherezade/hollows_hunter#2]
add pls

**Comment by hasherezade** [comment]
Hi! Thank you for the suggestion. I was thinking about it before, I think it is a good idea in general.
I am planning to add some simple signatures in the future. But I don't want to make it too heavy, because it would slow down the scan too much. So, only simple, binary signatures (like in PE-bear) - but no yara in-memory scan, and no regexes. Does it sound fine?

**Comment by lurumdare** [comment]
@hasherezade yes

**Comment by hasherezade** [comment]
ok, cool. It will be added after some time, please keep patient.

**Comment by lurumdare** [comment]
@hasherezade please see the project SigMaker https://github.com/ajkhoury/SigMaker-x64
